// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM_Case_Managemnt_API.Data;

#nullable disable

namespace PMCaseManagemntAPI.Migrations.DB
{
    [DbContext(typeof(DBContext))]
    [Migration("20230531115806_branchUpdate")]
    partial class branchUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Case.CaseIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedToStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ForwardedToEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IssueStatus")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByEmployeeId");

                    b.HasIndex("AssignedToEmployeeId");

                    b.HasIndex("AssignedToStructureId");

                    b.HasIndex("CaseId");

                    b.HasIndex("ForwardedToEmployeeId");

                    b.ToTable("CaseIssues");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicantType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerIdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.Appointement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSmsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Appointements");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.AppointementWithCalender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointementDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AppointementWithCalender");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AffairStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CaseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LetterNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetterSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Representative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<bool>("SMSStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("CaseTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FolderId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseAttachments");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AffairHistoryStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ForwardedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ForwardedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FromEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FromStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsConfirmedBySeretery")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForwardedBySeretery")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmsSent")
                        .HasColumnType("bit");

                    b.Property<int>("ReciverType")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevertedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<bool>("SecreateryNeeded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SecreteryConfirmationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SecreteryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SeenDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ToEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ToStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TransferedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("childOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("CaseTypeId");

                    b.HasIndex("ForwardedById");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("FromStructureId");

                    b.HasIndex("SecreteryId");

                    b.HasIndex("ToEmployeeId");

                    b.HasIndex("ToStructureId");

                    b.ToTable("CaseHistories");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseHistoryAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseHistoryId");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseHistoryAttachments");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseMessages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageFrom")
                        .HasColumnType("int");

                    b.Property<bool>("Messagestatus")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseMessages");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CaseForm")
                        .HasColumnType("int");

                    b.Property<string>("CaseTypeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Counter")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentCaseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<float>("TotlaPayment")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ParentCaseTypeId");

                    b.ToTable("CaseTypes");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.FileSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaseTypeId");

                    b.ToTable("FileSettings");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.FilesInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FileSettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("filetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("FileSettingId");

                    b.ToTable("FilesInformations");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.BudgetYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProgramBudgetYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramBudgetYearId");

                    b.ToTable("BudgetYears");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("MobileUsersMacaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationalStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalStructureId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("FolderName", "RowId")
                        .IsUnique();

                    b.ToTable("Folder");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.OrganizationBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHeadOffice")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationProfileId");

                    b.ToTable("OrganizationBranches");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.OrganizationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationNameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationNameInLocalLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<int>("SmsCode")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrganizationProfile");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBranch")
                        .HasColumnType("bit");

                    b.Property<string>("OfficeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrganizationBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentStructureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("StructureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationBranchId");

                    b.HasIndex("OrganizationProfileId");

                    b.HasIndex("ParentStructureId");

                    b.ToTable("OrganizationalStructures");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.ProgramBudgetYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FromYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<int>("ToYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProgramBudgetYears");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.Row", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ShelfId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShelfId");

                    b.HasIndex("RowNumber", "ShelfId")
                        .IsUnique();

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.Shelf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("ShelfNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShelfNumber")
                        .IsUnique();

                    b.ToTable("Shelf");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.StandardizedFormDocuments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("StandrizedFormId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StandrizedFormId");

                    b.ToTable("FormDocuments");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.StandrizedForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StandrizedForms");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.UnitOfMeasurment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasurment");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ActivityParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<float?>("ActualBudget")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("datetime2");

                    b.Property<float>("ActualWorked")
                        .HasColumnType("real");

                    b.Property<float>("Begining")
                        .HasColumnType("real");

                    b.Property<Guid?>("CommiteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("FieldWork")
                        .HasColumnType("real");

                    b.Property<float>("Goal")
                        .HasColumnType("real");

                    b.Property<float>("OfficeWork")
                        .HasColumnType("real");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PlanedBudget")
                        .HasColumnType("real");

                    b.Property<bool>("PostToCase")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShouldEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShouldStat")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnitOfMeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<int?>("targetDivision")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityParentId");

                    b.HasIndex("CommiteeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityParent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityParentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ActualBudget")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime2");

                    b.Property<float>("ActualWorked")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ActuallStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("Goal")
                        .HasColumnType("real");

                    b.Property<bool>("HasActivity")
                        .HasColumnType("bit");

                    b.Property<float>("PlanedBudget")
                        .HasColumnType("real");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShouldEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShouldStartPeriod")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("ActivityParents");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ActualBudget")
                        .HasColumnType("real");

                    b.Property<float>("ActualWorked")
                        .HasColumnType("real");

                    b.Property<string>("CoordinatorApprovalRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DirectorApprovalRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeValueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FinanceApprovalRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinanceDocumentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsApprovedByDirector")
                        .HasColumnType("int");

                    b.Property<int>("IsApprovedByFinance")
                        .HasColumnType("int");

                    b.Property<int>("IsApprovedByManager")
                        .HasColumnType("int");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuarterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<int>("progressStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EmployeeValueId");

                    b.HasIndex("QuarterId");

                    b.ToTable("ActivityProgresses");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityTargetDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<float>("Target")
                        .HasColumnType("real");

                    b.Property<float>("TargetBudget")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityTargetDivisions");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityTerminationHistories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApprovedByDirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FromEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("Isapproved")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<string>("TerminationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ToCommiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ToEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ApprovedByDirectorId");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("ToCommiteId");

                    b.HasIndex("ToEmployeeId");

                    b.ToTable("ActivityTerminationHistories");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Commitees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommiteeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Commitees");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.CommitesEmployees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommiteeEmployeeStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("CommiteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommiteeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CommiteEmployees");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.EmployeesAssignedForActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeesAssignedForActivities");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BudgetYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FinanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasTask")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PeriodEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PeriodStartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PlanWeight")
                        .HasColumnType("real");

                    b.Property<float>("PlandBudget")
                        .HasColumnType("real");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("StructureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BudgetYearId");

                    b.HasIndex("FinanceId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("StructureId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Programs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramBudgetYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProgramPlannedBudget")
                        .HasColumnType("real");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramBudgetYearId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ProgressAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityProgressId");

                    b.ToTable("ProgressAttachments");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.QuarterSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EndMonth")
                        .HasColumnType("int");

                    b.Property<string>("QuarterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuarterOrder")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuarterSettings");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("ActualBudget")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime2");

                    b.Property<float>("ActualWorked")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ActuallStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("Goal")
                        .HasColumnType("real");

                    b.Property<bool>("HasActivityParent")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PlanedBudget")
                        .HasColumnType("real");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShouldEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShouldStartPeriod")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.TaskMembers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityParentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskMembers");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.TaskMemo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivityParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActivityParentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PlanId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskMemos");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.TaskMemoReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskMemoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TaskMemoId");

                    b.ToTable("TaskMemoReplies");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Case.CaseIssue", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "AssignedByEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedByEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "AssignedToEmployee")
                        .WithMany()
                        .HasForeignKey("AssignedToEmployeeId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", "AssignedToStructure")
                        .WithMany()
                        .HasForeignKey("AssignedToStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "ForwardedToEmployee")
                        .WithMany()
                        .HasForeignKey("ForwardedToEmployeeId");

                    b.Navigation("AssignedByEmployee");

                    b.Navigation("AssignedToEmployee");

                    b.Navigation("AssignedToStructure");

                    b.Navigation("Case");

                    b.Navigation("ForwardedToEmployee");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.Appointement", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.AppointementWithCalender", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.Case", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.CaseType", "CaseType")
                        .WithMany()
                        .HasForeignKey("CaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId");

                    b.Navigation("Applicant");

                    b.Navigation("CaseType");

                    b.Navigation("Employee");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseAttachment", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseHistory", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", "Case")
                        .WithMany("CaseHistories")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.CaseType", "CaseType")
                        .WithMany()
                        .HasForeignKey("CaseTypeId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "ForwardedBy")
                        .WithMany()
                        .HasForeignKey("ForwardedById");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", "FromStructure")
                        .WithMany()
                        .HasForeignKey("FromStructureId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Secretery")
                        .WithMany()
                        .HasForeignKey("SecreteryId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "ToEmployee")
                        .WithMany()
                        .HasForeignKey("ToEmployeeId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", "ToStructure")
                        .WithMany()
                        .HasForeignKey("ToStructureId");

                    b.Navigation("Case");

                    b.Navigation("CaseType");

                    b.Navigation("ForwardedBy");

                    b.Navigation("FromEmployee");

                    b.Navigation("FromStructure");

                    b.Navigation("Secretery");

                    b.Navigation("ToEmployee");

                    b.Navigation("ToStructure");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseHistoryAttachment", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.CaseHistory", "CaseHistory")
                        .WithMany("Attachments")
                        .HasForeignKey("CaseHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", null)
                        .WithMany("CaseAttachments")
                        .HasForeignKey("CaseId");

                    b.Navigation("CaseHistory");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseMessages", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseType", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.CaseType", "ParentCaseType")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentCaseTypeId");

                    b.Navigation("ParentCaseType");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.FileSetting", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.CaseType", "CaseType")
                        .WithMany()
                        .HasForeignKey("CaseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseType");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.FilesInformation", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.CaseModel.FileSetting", "FileSetting")
                        .WithMany()
                        .HasForeignKey("FileSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("FileSetting");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.BudgetYear", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.ProgramBudgetYear", null)
                        .WithMany("BudgetYears")
                        .HasForeignKey("ProgramBudgetYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.Employee", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", "OrganizationalStructure")
                        .WithMany()
                        .HasForeignKey("OrganizationalStructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationalStructure");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.Folder", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Row", "Row")
                        .WithMany()
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Row");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.OrganizationBranch", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationProfile", "OrganizationProfile")
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationProfile");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationBranch", null)
                        .WithMany("structures")
                        .HasForeignKey("OrganizationBranchId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationProfile", "OrganizationProfile")
                        .WithMany()
                        .HasForeignKey("OrganizationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", "ParentStructure")
                        .WithMany("SubTask")
                        .HasForeignKey("ParentStructureId");

                    b.Navigation("OrganizationProfile");

                    b.Navigation("ParentStructure");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.Row", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Shelf", "Shelf")
                        .WithMany()
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.StandardizedFormDocuments", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.StandrizedForm", null)
                        .WithMany("StandardizedFormDocuments")
                        .HasForeignKey("StandrizedFormId");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Activity", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.ActivityParent", "ActivityParent")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityParentId");

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Commitees", "Commitee")
                        .WithMany()
                        .HasForeignKey("CommiteeId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Plan", "Plan")
                        .WithMany("Activities")
                        .HasForeignKey("PlanId");

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Task", "Task")
                        .WithMany("Activities")
                        .HasForeignKey("TaskId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.UnitOfMeasurment", "UnitOfMeasurement")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityParent");

                    b.Navigation("Commitee");

                    b.Navigation("Employee");

                    b.Navigation("Plan");

                    b.Navigation("Task");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityParent", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Task", "Task")
                        .WithMany("ActivitiesParents")
                        .HasForeignKey("TaskId");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityProgress", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Activity", "Activity")
                        .WithMany("ActProgress")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "EmployeeValue")
                        .WithMany()
                        .HasForeignKey("EmployeeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.ActivityTargetDivision", "Quarter")
                        .WithMany()
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("EmployeeValue");

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityTargetDivision", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Activity", "Activity")
                        .WithMany("ActivityTargetDivisions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityTerminationHistories", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "ApprovedByDirector")
                        .WithMany()
                        .HasForeignKey("ApprovedByDirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Commitees", "ToCommite")
                        .WithMany()
                        .HasForeignKey("ToCommiteId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "ToEmployee")
                        .WithMany()
                        .HasForeignKey("ToEmployeeId");

                    b.Navigation("Activity");

                    b.Navigation("ApprovedByDirector");

                    b.Navigation("FromEmployee");

                    b.Navigation("ToCommite");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.CommitesEmployees", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Commitees", "Commitee")
                        .WithMany("Employees")
                        .HasForeignKey("CommiteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.EmployeesAssignedForActivities", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Activity", "Activity")
                        .WithMany("AssignedEmploye")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Plan", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.BudgetYear", "BudgetYear")
                        .WithMany()
                        .HasForeignKey("BudgetYearId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Finance")
                        .WithMany()
                        .HasForeignKey("FinanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Programs", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", "Structure")
                        .WithMany()
                        .HasForeignKey("StructureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetYear");

                    b.Navigation("Finance");

                    b.Navigation("Program");

                    b.Navigation("ProjectManager");

                    b.Navigation("Structure");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Programs", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.ProgramBudgetYear", "ProgramBudgetYear")
                        .WithMany()
                        .HasForeignKey("ProgramBudgetYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramBudgetYear");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ProgressAttachment", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.ActivityProgress", "ActivityProgress")
                        .WithMany("ProgressAttachments")
                        .HasForeignKey("ActivityProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityProgress");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Task", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Plan", "Plan")
                        .WithMany("Tasks")
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.TaskMembers", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.ActivityParent", "ActivityParent")
                        .WithMany("TaskMember")
                        .HasForeignKey("ActivityParentId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Plan", "Plan")
                        .WithMany("TaskMember")
                        .HasForeignKey("PlanId");

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Task", "Task")
                        .WithMany("TaskMember")
                        .HasForeignKey("TaskId");

                    b.Navigation("ActivityParent");

                    b.Navigation("Employee");

                    b.Navigation("Plan");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.TaskMemo", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.PM.ActivityParent", "ActivityParent")
                        .WithMany("TaskMemos")
                        .HasForeignKey("ActivityParentId");

                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Plan", "Plan")
                        .WithMany("TaskMemos")
                        .HasForeignKey("PlanId");

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.Task", "Task")
                        .WithMany("TaskMemos")
                        .HasForeignKey("TaskId");

                    b.Navigation("ActivityParent");

                    b.Navigation("Employee");

                    b.Navigation("Plan");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.TaskMemoReply", b =>
                {
                    b.HasOne("PM_Case_Managemnt_API.Models.Common.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_Case_Managemnt_API.Models.PM.TaskMemo", "TaskMemo")
                        .WithMany("Replies")
                        .HasForeignKey("TaskMemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TaskMemo");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.Case", b =>
                {
                    b.Navigation("CaseAttachments");

                    b.Navigation("CaseHistories");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseHistory", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.CaseModel.CaseType", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.OrganizationBranch", b =>
                {
                    b.Navigation("structures");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.OrganizationalStructure", b =>
                {
                    b.Navigation("SubTask");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.ProgramBudgetYear", b =>
                {
                    b.Navigation("BudgetYears");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.Common.StandrizedForm", b =>
                {
                    b.Navigation("StandardizedFormDocuments");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Activity", b =>
                {
                    b.Navigation("ActProgress");

                    b.Navigation("ActivityTargetDivisions");

                    b.Navigation("AssignedEmploye");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityParent", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("TaskMember");

                    b.Navigation("TaskMemos");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.ActivityProgress", b =>
                {
                    b.Navigation("ProgressAttachments");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Commitees", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Plan", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("TaskMember");

                    b.Navigation("TaskMemos");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.Task", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ActivitiesParents");

                    b.Navigation("TaskMember");

                    b.Navigation("TaskMemos");
                });

            modelBuilder.Entity("PM_Case_Managemnt_API.Models.PM.TaskMemo", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
